name: finvu_flutter_sdk_demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  finvu_flutter_sdk:
    git:
      url: https://github.com/Cookiejar-technologies/finvu_flutter_sdk.git
      path: client
      ref: 1.0.6
  finvu_flutter_sdk_core:
    git:
      url: https://github.com/Cookiejar-technologies/finvu_flutter_sdk.git
      path: core
      ref: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

